import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans", });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.variable}>
        <ReduxProvider>
        <nav>
          <h1>Task Manager</h1>
        </nav>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
